# Generated by Django 4.2.5 on 2023-10-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Drinks',
        ),
    ]
