# Generated by Django 4.2.5 on 2023-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_drink_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(upload_to='drinks/', verbose_name='Изображение'),
        ),
    ]
